version: 2.1

# Définir les orbs
orbs:
  codecov: codecov/codecov@5

# Définir un job pour compiler et tester l'application
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0  # Utilisation d'une image Docker CircleCI OpenJDK
    steps:
      - checkout  # Récupérer le code
      - run:
          name: Build
          command: mvn -B -DskipTests clean package  # Nettoyer et construire sans exécuter les tests
      - run:
          name: Test
          command: mvn test  # Exécuter les tests

  # Job pour envoyer les résultats de couverture à Codecov
  upload-to-codecov:
    docker:
      - image: cimg/openjdk:17.0  # Même image Docker utilisée ici
    steps:
      - checkout  # Récupérer le code pour s'assurer que tous les fichiers sont disponibles
      - codecov/upload:  # Utilisation de l'orb Codecov pour télécharger les résultats de couverture
          token: CODECOV_TOKEN  # Passer la variable d'environnement

# Workflow pour orchestrer les jobs
workflows:
  version: 2
  build-and-upload:
    jobs:
      - build-and-test  # Exécuter d'abord le job de construction et tests
      - upload-to-codecov:  # Ensuite, envoyer les résultats à Codecov
          requires:
            - build-and-test  # Le job upload dépend du job build-and-test
