version: 2.1

# Définir les orbs
orbs:
  codecov: codecov/codecov@4.0.1

# Définir un job pour compiler et tester l'application
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0  # Utilisation d'une image Docker CircleCI OpenJDK
    steps:
      - checkout  # Récupérer le code
      - run:
          name: Build
          command: mvn -B -DskipTests clean package  # Nettoyer et construire sans exécuter les tests
      - run:
          name: Test
          command: mvn test  # Exécuter les tests
      - run:
          name: Jacoco file generation
          command: mvn jacoco:report
      - codecov/upload: # Utilisation de l'orb Codecov pour télécharger les résultats de couverture
          file: target/site/jacoco/jacoco.xml

      - run:
          name: Run Checkstyle and Generate Report
          command: mvn checkstyle:checkstyle
      - run:
          name: Copy Checkstyle Report to Output Directory
          command: |
            mkdir -p ~/reports/
            cp target/checkstyle-result.xml ~/reports/checkstyle-result.xml

#      - store_artifacts:
#          path: target/site
#          destination: reports

 # Récupérer le code pour s'assurer que tous les fichiers sont disponibles

# Workflow pour orchestrer les jobs
workflows:
  version: 2
  build-and-upload:
    jobs:
      - build-and-test  # Exécuter d'abord le job de construction et tests
